# Generated by Django 3.0.7 on 2020-06-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
