# Generated by Django 3.0.7 on 2020-06-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0002_auto_20200608_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='industry_type_subordinate',
            field=models.ManyToManyField(blank=True, null=True, to='Employer.IndustryTypeSubordinate'),
        ),
    ]
